# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudecm < Formula
  desc "One-command switch between Claude Code and Codex CLI configurations."
  homepage "https://github.com/a2d2-dev/claudecm"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/a2d2-dev/claudecm/releases/download/v1.1.0/claudecm_1.1.0_darwin_amd64.tar.gz"
      sha256 "94664c12fc1e8ac49f25aeaffb732ab0115090f36772bd60ab3540970386f8ed"

      def install
        bin.install "claudecm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/a2d2-dev/claudecm/releases/download/v1.1.0/claudecm_1.1.0_darwin_arm64.tar.gz"
      sha256 "a8a900c1d8106453f3cb3f57da0321c2baa21fd30089909790f5d040e98210c0"

      def install
        bin.install "claudecm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/a2d2-dev/claudecm/releases/download/v1.1.0/claudecm_1.1.0_linux_amd64.tar.gz"
      sha256 "ca55efc23a08dc36971c736dc22683ce49d56817f3c38050ca338f3fb02d2cd6"
      def install
        bin.install "claudecm"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/a2d2-dev/claudecm/releases/download/v1.1.0/claudecm_1.1.0_linux_arm64.tar.gz"
      sha256 "53e317de580d2b8416a875e8f2d88e05f2ea3658c7d898a2371648e51e50ec07"
      def install
        bin.install "claudecm"
      end
    end
  end

  test do
    system "#{bin}/claudecm", "version"
    system "#{bin}/claudecm", "--help"
  end
end
